GET {{host-url}}/product

###

GET {{host-url}}/cart

###

POST {{host-url}}/cart
Content-Type: application/json

{
  "productId": "B0001",
  "quantity": 4
}

###

POST {{host-url}}/login
Content-Type: application/json

{
  "username": "manager1@email.com",
  "password": "123",
  "rem": true
}

###

GET {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}


###

POST {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}

[
]

###

PUT {{host-url}}/cart/B0002
Content-Type: application/json
Authorization: Bearer {{token}}

1

###
POST {{host-url}}/cart/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantity": 4,
  "productId": "B0002"
}

###

DELETE {{host-url}}/cart/B0002
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST {{host-url}}/cart/checkout
Content-Type: application/json
Authorization: Bearer {{token}}


###

GET {{host-url}}/order/finish/2147483643
Authorization: Bearer {{token}}

###

GET {{host-url}}/order/2147483643
Authorization: Bearer {{token}}

###

GET {{host-url}}/profile/manager1@email.com
Authorization: Bearer {{token}}



###

PUT {{host-url}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "00001",
  "email": "cliente001@email.com",
  "password": "1234",
  "name": "cliente1",
  "phone": "3394624856",
  "address": "Via Riccardo Misasi, 5",
  "active": false,
  "role": "ROLE_CUSTOMER",
  "authorities": [
    {
      "authority": "ROLE_CUSTOMER"
    }
  ]
}

###

GET {{host-url}}/product/B0003

Content-Type: application/json
Authorization: Bearer {{token}}

###

PUT {{host-url}}/seller/product/B0002/edit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "CS-BR CVS0003",
  "productName": "Cosenza - Brescia ",
  "productPrice": 16.00,
  "productStock": 5200,
  "productDescription": "33° Giornata di Serie B",
  "productIcon": "https://backendcdn.vivaticket.it/img_eventi_new/COSENZA_BRESCIA_67f63726894fd.png",
  "productStatus": 0,
  "categoryType": 0,
  "updateTime": "2025-04-10 19:42:02"
}

###

POST {{host-url}}/seller/product/new
Content-Type: application/json
Authorization: Bearer {{token}}



{
  "productId": "CS-BR CVS2003",
  "productName": "Cosenza - Brescia ",
  "productPrice": 16.00,
  "productStock": 5200,
  "productDescription": "33° Giornata di Serie B",
  "productIcon": "https://backendcdn.vivaticket.it/img_eventi_new/COSENZA_BRESCIA_67f63726894fd.png",
  "productStatus": 0,
  "categoryType": 0,
  "updateTime": "2025-04-10 19:42:02"
}

###
