spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Matteo_7
    url: jdbc:postgresql://localhost:5432/shopApi
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: venditaBigliettiCS.shop
jwtExpiration: 86400
